export const SUBMIT_CHARACTERISTICS = 'SUBMIT_CHARACTERISTICS';
export const SUBMIT_GOAL_RATIO = 'SUBMIT_GOAL_RATIO';
export const SUBMIT_NUTRITION_RATIO = 'SUBMIT_NUTRITION_RATIO';
export const CHARACTERISTICS_INPUT_CHANGE = 'CHARACTERISTICS_INPUT_CHANGE';

export const CALCULATE_TOTAL_INTAKE = 'CALCULATE_TOTAL_INTAKE';
export const CALCULATE_GOAL_NUTRITION = 'CALCULATE_GOAL_NUTRITION';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_MEAL_TO_TABLE = 'ADD_MEAL_TO_TABLE';

export const ActionNames = Object.freeze({
    SUBMIT_CHARACTERISTICS,
    SUBMIT_GOAL_RATIO,
    SUBMIT_NUTRITION_RATIO,
    CHARACTERISTICS_INPUT_CHANGE,
});
